project:
  type: website
  output-dir: docs
  render:
    - content/density_impact.qmd
    - content/summary_rodriguez.qmd

website:
  title: "Random ILR Thesis"
  navbar:
    left:
      - text: "Density Impact"
        file: content/density_impact.qmd
      - text: "Rodriguez Summary"
        file: content/summary_rodriguez.qmd

format:
  html:
    theme: cosmo
    toc: true

