project:
  type: website
  output-dir: docs
  render:
    - content/density_impact.qmd
    - content/summary_rodriguez_pc_half.qmd
    - content/summary_rodriguez_pc_max_lib_size.qmd
    - content/summary_random_ilr_pc_half.qmd

website:
  title: "Random ILR Thesis"
  navbar:
    left:
      - text: "Density Impact"
        file: content/density_impact.qmd
      - text: "Rodriguez Summary - PC 0.5"
        file: content/summary_rodriguez_pc_half.qmd
      - text: "Rodriguez Summary - PC 1/MLS"
        file: content/summary_rodriguez_pc_max_lib_size.qmd
      - text: "Random ILR Summary - PC 0.5"
        file: content/summary_random_ilr_pc_half.qmd

format:
  html:
    theme: cosmo
    toc: true

